### ISSUE TITLE
Contacts from Fruux creates no events

### ISSUE THREAD

**Issue by simmel** [SufficientlySecure/birthday-adapter#81]
**What steps will reproduce the problem?**
1. Have all your contacts in [Fruux](https://fruux.com) and make them available on your phone via [their app](https://play.google.com/store/apps/details?id=com.fruux.android)
2. Install Birthday Adapter
3. Disable Privacy Guard for Birthday Adapter
4. Start Birthday Adapter (and if it doesn't start automatically, start syncing)

**What is the expected output?**
I expect my contacts birthdays to appear in the Birthday calendar.

**What do you see instead?**
No events appear in the calendar.

**What version of the product are you using? On what operating system?**
Android 4.3.1 via CyanogenMod 10.2.1-maguro (Galaxy Nexus)

**Please provide any additional information below.**
This output from ``adb -d logcat``:
```
I/ActivityManager(  953): Start proc org.birthdayadapter.free:calendar for service org.birthdayadapter.free/org.birthdayadapter.service.CalendarSyncAdapterService: pid=31597 uid=10087 gids={50087, 1028}
E/JavaBinder(31597): !!! FAILED BINDER TRANSACTION !!!
E/Birthday Adapter(31597): Applying batch error!
E/Birthday Adapter(31597): android.os.TransactionTooLargeException
E/Birthday Adapter(31597): 	at android.os.BinderProxy.transact(Native Method)
E/Birthday Adapter(31597): 	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:482)
E/Birthday Adapter(31597): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:227)
E/Birthday Adapter(31597): 	at android.content.ContentResolver.applyBatch(ContentResolver.java:951)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService.performSync(CalendarSyncAdapterService.java:860)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService.performSync(CalendarSyncAdapterService.java:697)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService.access$000(CalendarSyncAdapterService.java:65)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService$SyncAdapterImpl.onPerformSync(CalendarSyncAdapterService.java:86)
E/Birthday Adapter(31597): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
E/JavaBinder(31597): !!! FAILED BINDER TRANSACTION !!!
E/Birthday Adapter(31597): Applying batch error!
E/Birthday Adapter(31597): android.os.TransactionTooLargeException
E/Birthday Adapter(31597): 	at android.os.BinderProxy.transact(Native Method)
E/Birthday Adapter(31597): 	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:482)
E/Birthday Adapter(31597): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:227)
E/Birthday Adapter(31597): 	at android.content.ContentResolver.applyBatch(ContentResolver.java:951)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService.performSync(CalendarSyncAdapterService.java:860)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService.performSync(CalendarSyncAdapterService.java:697)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService.access$000(CalendarSyncAdapterService.java:65)
E/Birthday Adapter(31597): 	at org.birthdayadapter.service.CalendarSyncAdapterService$SyncAdapterImpl.onPerformSync(CalendarSyncAdapterService.java:86)
E/Birthday Adapter(31597): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
[...] repeats *a lot* of times
```

**Comment by simmel** [comment]
Since this is so old and CM10 isn't supported any more, I'm guessing, let's close this and clean up the issues.
