### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/birthday-adapter#91]
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65578, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.birthdayadapter.free/org.birthdayadapter.ui.BaseActivity}: java.lang.SecurityException: uid 10212 cannot explicitly add accounts of type: org.birthdayadapter.account
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.SecurityException: uid 10212 cannot explicitly add accounts of type: org.birthdayadapter.account
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:995)
	at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:733)
	at org.birthdayadapter.util.AccountHelper.addAccount(AccountHelper.java:65)
	at org.birthdayadapter.util.AccountHelper.addAccountAndSync(AccountHelper.java:79)
	at org.birthdayadapter.ui.BasePreferenceFragment.onRequestPermissionsResult(BasePreferenceFragment.java:116)
	at android.support.v4.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:911)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7069)
	at android.app.Activity.dispatchActivityResult(Activity.java:6921)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
	... 9 more
```

**Comment by abirke** [comment]
This is most probably related to #96. It might also be targeted by #108 but I only have one Android version available to test so somebody might double-check.
